# Distributed under the MIT License.
# See LICENSE.txt for details.

# The online TravisCI configuration:
#
# General:
# - Build only if .travis.yml is present: ON
# - Build branch updates: ON
# - Build pull request updates: ON
# - Limit concurrent jobs: OFF
#
# Auto Cancellation:
# - Auto cancel branch builds: ON
# - Auto cancel pull request builds: ON
#
# Environment Variables:
# - COVERALLS_TOKEN: Sign up to coveralls and link to GitHub. Add the
#                    repository you want to display, and copy the repo_token.
#                    The repo_token is what COVERALLS_TOKEN must be set to.
# - ENCRYPTION_LABEL:
#      The file encryption mechanism of TravisCI is used to encrypt the private
#      SSH key we need to push to the gh-pages branch of the repository. Follow
#      the instructions on Travis:
#      https://docs.travis-ci.com/user/encrypting-files/
#      to install the `travis` executable. You can then run
#      `travis encrypt-file -r sxs-collaboration/spectre deploy_key`
#      replacing `sxs-collaboration/spectre` with whatever repo you want. Here
#      `deploy_key` is the SSH key added to the GitHub repo's Deploy Keys
#      (see the GitHub docs for info on deploy keys). Once you've run the
#      `encrypt-file` command you will have two environment variables appear,
#      `encrypted_${ENCRYPTION_LABEL}_iv` and
#      `encrypted_${ENCRYPTION_LABEL}_key` where ${ENCRYPTION_LABEL} is an
#      alpha-numerical combination that you will set the Travis
#      `ENCRYPTION_LABEL` environment variable to (you'll need to add this
#      variable manually).
#
# Cron Jobs:
# - Branch: develop, Interval: daily, Options: Always run

language: cpp

# To use Docker we need root access
sudo: required

services:
- docker

# Set up travis configurations of Linux and macOS. We use the 14.04 Ubuntu build
# env. We target 10.11 Debug and 10.12 Release builds.
#
# We also have separate targets for running shell scripts that enforce what
# would normally be done as pre-push hooks, CHECK_COMMITS and CHECK_FILES
#
# We run two static analyzers, and clang-tidy.
#
# NOTE: The static analysis targets are run first since these are typically
#       fast to run and provide the most useful feedback.
matrix:
  fast_finish: true
  include:
  - os: linux
    dist: trusty
    env: CHECK_COMMITS=true
    compiler: clang
  - os: linux
    dist: trusty
    env: CHECK_FILES=true
    compiler: clang
  - os: linux
    dist: trusty
    env: RUN_CLANG_TIDY=true BUILD_TYPE=Release
    compiler: clang
  - os: linux
    dist: trusty
    env: RUN_CLANG_TIDY=true BUILD_TYPE=Debug
    compiler: clang
  - os: linux
    dist: trusty
    env: RUN_IWYU=true BUILD_TYPE=Debug
    compiler: clang
  - os: linux
    dist: trusty
    env: TEST_CHECK_FILES=true
    compiler: clang
    # Run full builds after static analysis
  - os: linux
    compiler: gcc
    dist: trusty
    env: BUILD_TYPE=Debug COVERAGE=ON
  - os: linux
    compiler: gcc
    dist: trusty
    env: BUILD_TYPE=Release
  - os: linux
    compiler: gcc-6
    dist: trusty
    env: BUILD_TYPE=Debug COMPILER=gcc-6
  - os: linux
    compiler: gcc-6
    dist: trusty
    env: BUILD_TYPE=Release COMPILER=gcc-6
  - os: linux
    compiler: clang
    dist: trusty
    env: BUILD_TYPE=Debug
  - os: linux
    compiler: clang
    dist: trusty
    env: BUILD_TYPE=Release
  - os: osx
    env: BUILD_TYPE=Debug
    osx_image: xcode8.3
    compiler: clang
  - os: osx
    osx_image: xcode8.3
    env: BUILD_TYPE=Release
    compiler: clang


# Travis allows caching of data between builds to reduce build times or perform
# regression testing. We use ccache (https://ccache.samba.org/) to reduce
# compilation time.
cache:
  ccache: true

# For macOS we install all dependencies in the before_install step of Travis.
# Unfortunately installing ccache and jemalloc from brew causes a brew update,
# which is extremely slow. For some reason ccache isn't building correctly when
# cloned and installed. The minimum version of macOS is set to 10.11 to avoid
# linking errors. All dependencies are installed into the home directory.
# ccache is used to reduce build times.
before_install:
  - export CHARM_PATCH=v6.8.patch
  - export CHARM_CC=${CC}
  - export FC=gfortran
  - if [[ ${COMPILER} =~ (gcc|clang)-([0-9\.]+) ]]; then
      CC=${BASH_REMATCH[1]}-${BASH_REMATCH[2]};
      if [[ ${BASH_REMATCH[1]} = gcc ]]; then
          CXX=g++-${BASH_REMATCH[2]};
          FC=gfortran-${BASH_REMATCH[2]};
      else
          CXX=clang++-${BASH_REMATCH[2]};
      fi
    fi
  - if [ ${RUN_IWYU} ]; then
        export USE_PCH=OFF;
    else
        export USE_PCH=ON;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export CHARM_VERSION=6.8.0;
      export BLAZE_VERSION=3.2;
      export HDF5_VERSION=1.8.17;
      export NUMPY_VERSION=1.14;
      export SPECTRE_MIN_MACOS=-mmacosx-version-min=10.11;
      cd $HOME;
      rm /usr/local/include/c++;
      brew update;
      brew install gcc;
      brew install ccache;
      PATH=/usr/local/opt/ccache/libexec:$PATH;
      brew install jemalloc;
      brew install gsl;
      brew install hdf5;

      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      chmod +x miniconda.sh;
      ./miniconda.sh -b -p /Users/travis/mc;
      export PATH=/Users/travis/mc/bin:$PATH;
      conda info;
      conda update --yes conda;
      conda create -n osx_env --yes python=$TRAVIS_PYTHON_VERSION;
      source activate osx_env;
      conda install -y numpy=$NUMPY_VERSION;

      ccache -z;
      git clone https://github.com/hfp/libxsmm.git;
      cd libxsmm && git checkout 1.8.1;
      mkdir build && cd build && make -f ../Makefile;
      ccache -s;
      cd $HOME;

      git clone https://github.com/philsquared/Catch.git;
      cd Catch;
      git checkout v2.1.2;
      cd $HOME;

      git clone https://github.com/edouarda/brigand.git;

      wget https://bitbucket.org/blaze-lib/blaze/downloads/blaze-${BLAZE_VERSION}.tar.gz;
      tar -xzf blaze-${BLAZE_VERSION}.tar.gz;

      if [ "$(sw_vers -productVersion | cut -d '.' -f 1,2)" = "10.12" ]; then
        printf "#ifndef _MACH_PORT_T\n#define _MACH_PORT_T\n#include <sys/_types.h> /* __darwin_mach_port_t */\ntypedef __darwin_mach_port_t mach_port_t;\n#include <pthread.h>\nmach_port_t pthread_mach_thread_np(pthread_t);\n#endif /* _MACH_PORT_T */" > ./new_threads;
        cat /Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support >> ./new_threads;
        sudo mv ./new_threads /Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support;
      fi

      ccache -z;
      wget http://charm.cs.illinois.edu/distrib/charm-${CHARM_VERSION}.tar.bz2;
      tar -xjf charm-${CHARM_VERSION}.tar.bz2;
      cd ./charm-${CHARM_VERSION};
      ./build charm++ multicore-darwin-x86_64 -j2 -O0 $SPECTRE_MIN_MACOS;
      git apply $TRAVIS_BUILD_DIR/support/Charm/${CHARM_PATCH};
      ccache -s;
      cd $HOME;

      ccache -z;
      git clone https://github.com/jbeder/yaml-cpp.git;
      cd ./yaml-cpp;
      mkdir lib;
      cd ./lib;
      cmake -DBUILD_SHARED_LIBS=ON ../;
      make -j2;
      ccache -s;
      cd $HOME;
    fi

# We use different configs for Linux and macOS. For Linux we use a Docker
# container to build SpECTRE, and build natively on macOS.
# The ENCRYPTED_KEY_VAR and ENCRYPTED_IV_VAR are used to retrieve the encrypted
# variables from TravisCI without showing the encrypt ID (which could be public
# without losing much, if any security). The COVERALLS_TOKEN is a
# secret env variable set in the TravisCI configuration.
#
# Linux:
# Use the folder ${HOME}/docker to hold the directories we need copied into the
# Docker image and also the Dockerfiles that are in the `containers` directory
# of the repo. The initial directory is inside the ${TRAVIS_BUILD_DIR}. We move
# the repo into the docker directory, and then copy in cached files. The
# known_hosts is copied in so that the image has push access to gh-pages in
# a secure manner. The GH_PAGES variables are used for automatic deployment of
# documentation to GitHub pages.  We compile with -march=x86-64 because Travis
# puts us on different hardware sometimes and that breaks ccache if we use
# -march=native.
#
# macOS:
# The variable ${TRAVIS_BUILD_DIR} points to the cloned repository, not what
# we would normally call the build dir, but actually the source dir.
#
# What's the deal with all the &&?
# TravisCI only sees the return code of the last command executed inside the
# if block so a && between all the commands to execute returns the and of all
# the results. Thus, if any individual step fails, the build is failed.
script:
- ENCRYPTED_KEY_VAR="encrypted_${ENCRYPTION_LABEL}_key"
- ENCRYPTED_IV_VAR="encrypted_${ENCRYPTION_LABEL}_iv"
- export UPSTREAM_REPO="https://github.com/sxs-collaboration/spectre.git"
- export UPSTREAM_BRANCH="develop"
- export GH_PAGES_REPO="git@github.com:sxs-collaboration/spectre.git"
- export GH_PAGES_SOURCE_BRANCH="develop"
- printenv
- if [ "${CHECK_COMMITS}" == "true" ]; then
    ./tools/CheckCommits.sh;
  elif [ "${CHECK_FILES}" ==  "true" ]; then
    ./tools/CheckFiles.sh;
  elif [ "${TEST_CHECK_FILES}" ==  "true" ]; then
    ./tools/CheckFiles.sh --test;
  elif [ "${TRAVIS_OS_NAME}" == "linux" ]; then
    cp -vr containers ${HOME}/docker
    && cd ${HOME}
    && mv -v ${TRAVIS_BUILD_DIR} ${HOME}/docker/spectre
    && cp -r ${HOME}/.ccache ${HOME}/docker/ccache
    && cp ${HOME}/.ssh/known_hosts ${HOME}/docker/known_hosts
    && docker build
        --build-arg CXXFLAGS="-Werror -march=x86-64"
        --build-arg COVERAGE=${COVERAGE}
        --build-arg BUILD_TYPE=${BUILD_TYPE}
        --build-arg CC=${CC}
        --build-arg CXX=${CXX}
        --build-arg FC=${FC}
        --build-arg CHARM_CC=${CHARM_CC}
        --build-arg TRAVIS_BRANCH=${TRAVIS_BRANCH}
        --build-arg TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
        --build-arg TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
        --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
        --build-arg TRAVIS_TAG=${TRAVIS_TAG}
        --build-arg TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
        --build-arg TRAVIS_COMMIT=${TRAVIS_COMMIT}
        --build-arg TRAVIS_SECURE_ENV_VARS=${TRAVIS_SECURE_ENV_VARS}
        --build-arg TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE}
        --build-arg ENCRYPTED_KEY=${!ENCRYPTED_KEY_VAR}
        --build-arg ENCRYPTED_IV=${!ENCRYPTED_IV_VAR}
        --build-arg GH_PAGES_REPO=${GH_PAGES_REPO}
        --build-arg GH_PAGES_SOURCE_BRANCH=${GH_PAGES_SOURCE_BRANCH}
        --build-arg COVERALLS_TOKEN=${COVERALLS_TOKEN}
        --build-arg RUN_CLANG_TIDY=${RUN_CLANG_TIDY}
        --build-arg RUN_CPPCHECK=${RUN_CPPCHECK}
        --build-arg RUN_IWYU=${RUN_IWYU}
        --build-arg USE_PCH=${USE_PCH}
        --build-arg UPSTREAM_REPO=${UPSTREAM_REPO}
        --build-arg UPSTREAM_BRANCH=${UPSTREAM_BRANCH}
        --build-arg CHARM_PATCH=${CHARM_PATCH}
        -t ${TRAVIS_REPO_SLUG}
        -f ${HOME}/docker/Dockerfile.travis
        ${HOME}/docker/
    && rm -rf ${HOME}/.ccache
    && CON=$(docker run -d ${TRAVIS_REPO_SLUG} /bin/bash)
    && docker cp ${CON}:/root/.ccache ${HOME}/
    && docker cp ${CON}:/work/build_${BUILD_TYPE}_${CC}/tmp/coverage.info
                 ${HOME}/docker/spectre;
  elif [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    cd $HOME
    && mkdir build_${TRAVIS_OS_NAME}_${BUILD_TYPE}
    && cd ./build_${TRAVIS_OS_NAME}_${BUILD_TYPE}
    && ccache -z
    && cmake -D CHARM_ROOT=$HOME/charm-${CHARM_VERSION}
             -D BLAZE_ROOT=$HOME/blaze-${BLAZE_VERSION}/
             -D BRIGAND_ROOT=$HOME/brigand
             -D CATCH_ROOT=$HOME/Catch
             -D LIBXSMM_ROOT=$HOME/libxsmm/build
             -D YAMLCPP_ROOT=$HOME/yaml-cpp/
             -D MACOSX_MIN=10.11
             -D CMAKE_BUILD_TYPE=${BUILD_TYPE}
             ${TRAVIS_BUILD_DIR}
    && make test-executables -j2
    && ctest --output-on-failure
    && ccache -s;
  else
    echo "Unknown build environment"
    && exit -1;
  fi

# After a successful build the results are pushed to codecov.io, which doesn't
# use a token but instead tracks the repository name on GitHub. This allows it
# to report before being merged instead of after merging like Coveralls.
after_success:
- if [ ${TRAVIS_OS_NAME} = linux ]
  && [ ${CC} = gcc ]
  && [ ${COVERAGE} = ON ]; then
    cd ${HOME}/docker/spectre;
    bash <(curl -s https://codecov.io/bash) ||
         echo "Codecov did not collect coverage reports";
  fi

# Generated using instructions from:
# https://docs.travis-ci.com/user/notifications/#Slack-notifications
notifications:
  slack:
    secure: PntVovViQom/qkRd7K1wne6ji+3hn67bnrrfRZJ03LYk0PQUBgjNAQQAwEYqGOGeLlCEcKz1rQljUGaYFP5DYtu5BsXeWenSXbNElwfVivzHtEBdS9v4BnB4C0aD5hG2fzXhsbm4bAEq+fTfmyvHTbC8f7pHUV9zfJv4+yTjR0YW+0lYgtODqpxqEGC+f07RwkbsODO87yrZT9oPWZ8Q7a7ZECKcdv38oaBzN3cnHjFXsWTRYTu672FtBKefRohpS01UrobJNAM0L7Bl1huoP52rMw34J6Nl47u+upP/t/iPHi68lk8/0hRf0z+KgOYLSgGb5wwPfNQ9rrOfA1YTjCgVoyj/3pszP6mcVfXN40+5tjww7/RXsuQ+WsbEhOs9Z1cDAdPA0cd3pVb3Iv4an07htNfhLnaATtDe22BbuWD16LCUz/xVrq5XwWtE172EYWk7wyUZd8iofGXLLu/tVLs4lwZG/z1cF4wShpxhK3eXH3V4Y1wR7afpkzTN+z5Y4z5ObqDVMfydg79F4coaH0ky5K30Wf4n9TQ2yaDXIP3yepXBlpY1zXM0Ygmu9W2P5PCd79E5lWoWXoWwa90KmcOeuZ/CSbotHLCiAtzoDHjR70TOkPqEpGmnUubwhcYDnoNXv634FvZvExd97LeAuOlD9xcLUQRQKABVvj04S4k=
