var searchData=
[
  ['valid',['valid',['http://en.cppreference.com/w/cpp/thread/future/valid.html',1,'std::future::valid()'],['http://en.cppreference.com/w/cpp/thread/packaged_task/valid.html',1,'std::packaged_task::valid()'],['http://en.cppreference.com/w/cpp/thread/shared_future/valid.html',1,'std::shared_future::valid()']]],
  ['value',['value',['http://en.cppreference.com/w/cpp/error/error_code/value.html',1,'std::error_code::value()'],['http://en.cppreference.com/w/cpp/error/error_condition/value.html',1,'std::error_condition::value()'],['http://en.cppreference.com/w/cpp/experimental/optional/value.html',1,'std::experimental::optional::value()'],['http://en.cppreference.com/w/cpp/utility/optional/value.html',1,'std::optional::value()'],['http://en.cppreference.com/w/cpp/regex/regex_traits/value.html',1,'std::regex_traits::value()'],['../classTime.html#ad0c8c55e27a0978f532824b24e4b2244',1,'Time::value()'],['../classTimeDelta.html#ac4ee79784ce7a81ea454a0d1254d3821',1,'TimeDelta::value()'],['../classContinuedFractionSummer.html#a4025746080639fbc1551383e5e38f885',1,'ContinuedFractionSummer::value()']]],
  ['value_5fcomp',['value_comp',['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/map/value_comp.html',1,'std::pmr::map::value_comp()'],['http://en.cppreference.com/w/cpp/container/multimap/value_comp.html',1,'std::pmr::multimap::value_comp()'],['http://en.cppreference.com/w/cpp/container/multiset/value_comp.html',1,'std::pmr::multiset::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::pmr::set::value_comp()'],['http://en.cppreference.com/w/cpp/container/set/value_comp.html',1,'std::set::value_comp()']]],
  ['value_5for',['value_or',['http://en.cppreference.com/w/cpp/experimental/optional/value_or.html',1,'std::experimental::optional::value_or()'],['http://en.cppreference.com/w/cpp/utility/optional/value_or.html',1,'std::optional::value_or()']]],
  ['valueless_5fby_5fexception',['valueless_by_exception',['http://en.cppreference.com/w/cpp/utility/variant/valueless_by_exception.html',1,'std::variant']]],
  ['variables',['variables',['../classScalarWave_1_1Solutions_1_1PlaneWave.html#a2e0cf50aa10bdd8f41cfd9f7e65fba13',1,'ScalarWave::Solutions::PlaneWave::variables(const tnsr::I&lt; DataVector, Dim &gt; &amp;x, double t, tmpl::list&lt; ScalarWave::Pi, ScalarWave::Phi&lt; Dim &gt;, ScalarWave::Psi &gt;) const noexcept'],['../classScalarWave_1_1Solutions_1_1PlaneWave.html#a0456d388c3f80995d9200b570cce4ccb',1,'ScalarWave::Solutions::PlaneWave::variables(const tnsr::I&lt; DataVector, Dim &gt; &amp;x, double t, tmpl::list&lt; Tags::dt&lt; ScalarWave::Pi &gt;, Tags::dt&lt; ScalarWave::Phi&lt; Dim &gt;&gt;, Tags::dt&lt; ScalarWave::Psi &gt;&gt;) const noexcept'],['../classVariables_3_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html#a173ab7c95a5c3f506e1f41aaef5d9f9d',1,'Variables&lt; tmpl::list&lt; Tags... &gt; &gt;::Variables() noexcept'],['../classVariables_3_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html#a58e329bdac22e4201855ef599245780e',1,'Variables&lt; tmpl::list&lt; Tags... &gt; &gt;::Variables(Variables&lt; tmpl::list&lt; WrappedTags... &gt;&gt; &amp;&amp;rhs) noexcept'],['../classVariables_3_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html#aa218e9064f387aa34bd75621ec772f8d',1,'Variables&lt; tmpl::list&lt; Tags... &gt; &gt;::Variables(const Variables&lt; tmpl::list&lt; WrappedTags... &gt;&gt; &amp;rhs) noexcept'],['../classVariables_3_01tmpl_1_1list_3_01Tags_8_8_8_01_4_01_4.html#aac3891701120b1bc44af116264a1ad9e',1,'Variables&lt; tmpl::list&lt; Tags... &gt; &gt;::Variables(const blaze::Vector&lt; VT, VF &gt; &amp;expression) noexcept']]],
  ['variant',['variant',['http://en.cppreference.com/w/cpp/utility/variant/variant.html',1,'std::variant']]],
  ['vector',['vector',['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::pmr::vector::vector()'],['http://en.cppreference.com/w/cpp/container/vector/vector.html',1,'std::vector::vector()']]],
  ['velocity',['velocity',['../namespaceNewtonianEuler.html#a50c2df2cb04c9d8cc10157022324e126',1,'NewtonianEuler::velocity(gsl::not_null&lt; tnsr::I&lt; DataType, Dim &gt; *&gt; velocity, const Scalar&lt; DataType &gt; &amp;mass_density, const tnsr::I&lt; DataType, Dim &gt; &amp;momentum_density) noexcept'],['../namespaceNewtonianEuler.html#acd9f0015ee35bdb603c1791ae7a99ba7',1,'NewtonianEuler::velocity(const Scalar&lt; DataType &gt; &amp;mass_density, const tnsr::I&lt; DataType, Dim &gt; &amp;momentum_density) noexcept']]],
  ['volume_5foffset',['volume_offset',['../classSliceIterator.html#ae81dd0b41c36f65c851fb16e847b41cf',1,'SliceIterator']]],
  ['volumefile',['VolumeFile',['../classvis_1_1VolumeFile.html#ab903b9fed7318aa2a68d37fd46ddea4c',1,'vis::VolumeFile']]]
];
